VPN Topology description update
IETF-OPSAWG-WG/l3nm pull request #173
Opened 2020-07-03 09:51 UTC by sbarguil

2020-07-03 12:16 UTC, boucadair commented on yang/IETF-04/ietf-vpn-common.yang
> +      policies. The custom topology, reflects more complex
```suggestion
      policies. The custom topology reflects more complex 
```

2020-07-03 12:17 UTC, boucadair commented on yang/IETF-04/ietf-vpn-common.yang
> +      VPN-Nodes. For example, VPN-Node that acts as Hub for
```suggestion
     VPN nodes such as VPN node that acts as Hub for 
```

2020-07-03 12:21 UTC, boucadair commented
@sbarguil: Please link this one to issue #40. Thank you.

2020-09-17 16:20 UTC, oscargdd requested changes
"Identity for custom VPN topologies where the role of the nodes is not strictly hub or spoke.

2020-09-24 12:29 UTC, oscargdd approved these changes

2020-09-24 12:29 UTC, merged